### ISSUE TITLE
The name of this org needs to be changed. 

### ISSUE THREAD

**Issue by MikeCodesDotNET** [MicroSugarDeveloperOrg/Avalonia.WebView#1]
Hi, 

The name of this org and the usage of our branding could create confusion and make people think that this is associated with Avalonia UI. Can you please email me at mike@avaloniaui.net to discuss.

**Comment by ChisterWu** [comment]
I am very sorry, I have modified my organization name.

**Comment by MikeCodesDotNET** [comment]
> I am very sorry, I have modified my organization name.

No problem! Thank you for understanding. We love your work!
